export enum Category {
  CPU = 'PROCESSADOR',
  GPU = 'PLACA DE VÍDEO',
  MEMORY = 'MEMÓRIA',
  SSD = 'SSD',
  MONITOR = 'MONITOR',
  NOTEBOOK = 'NOTEBOOK',
  MOUSE = 'MOUSE',
  KEYBOARD = 'TECLADO',
  HEADSET = 'HEADSET',
}
